[package]
name = "service"
authors = [ 
    "veryCrunchy",
    "Jayden Andrews"
]

version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo", "derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
zmq = "0.10.0"
